### ISSUE TITLE
Mapa Mental

### ISSUE THREAD

**Issue by JoseABCruz** [SistemasTecTlaxiaco/actividad-1-mapa-mental-JoseABCruz#1]

**Comment by JoseABCruz** [comment]
[Mapa Mental (José Antonio Balbuena Cruz 6US).pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-mapa-mental-JoseABCruz/files/10575382/Mapa.Mental.Jose.Antonio.Balbuena.Cruz.6US.pdf)

**Comment by mel-16** [comment]
20% MUY BIEN

**Comment by josealfredo79** [comment]
Bien hecho y revisado
